//! Retained-mode UI built around Taffy.
//!
//! Containers own layout. Leaf controls implement [`Widget`].

use micromath::F32Ext;
mod geometry;
pub mod layout;
pub mod theme;
mod widget;
pub mod widgets;

use alloc::{boxed::Box, vec::Vec};
use embedded_graphics::{prelude::*, primitives::{PrimitiveStyle, Rectangle}};
use taffy::{geometry::Size as TSize, prelude::{AvailableSpace, Dimension, LengthPercentage as LP, LengthPercentageAuto as LPA}, tree::TaffyTree, Overflow, TraversePartialTree};
use crate::wm::{Window, WmEvent, EV_KEY_DOWN, EV_KEY_UP, EV_MOUSE_DOWN, EV_MOUSE_MOVE, EV_MOUSE_UP};
pub use geometry::{Constraints, Rect};
pub use taffy::prelude::{AlignContent, AlignItems, FlexDirection, JustifyContent, Position, Style};
pub use taffy::tree::NodeId;
pub use theme::{BG, BTN_BG, BTN_BG_DOWN, BTN_BG_HOT, BTN_BORDER, INPUT_BG, INPUT_BORDER, INPUT_BORDER_FOCUS, LABEL_FG, PANEL_BG, PANEL_BORDER, SCROLLBAR_BG, SCROLLBAR_THUMB, TEXT};
pub use widget::{EventResult, Widget};
pub use widgets::{Button, Label, TextInput};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UiEvent { Down { x: i32, y: i32 }, Move { x: i32, y: i32 }, Up { x: i32, y: i32 }, KeyDown { scancode: u8, ch: u8, mods: u8 }, KeyUp { scancode: u8, ch: u8, mods: u8 } }
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)] pub struct WidgetId(usize);
impl WidgetId { pub const fn index(self) -> usize { self.0 } }
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)] pub struct ScrollViewId(usize);
impl ScrollViewId { pub const fn index(self) -> usize { self.0 } }
#[derive(Clone, Copy)] enum NodeCtx { Widget(WidgetId), Panel, ScrollView(ScrollViewId), ScrollContent(ScrollViewId) }
#[derive(Clone, Copy, Debug, Default)] struct ScrollState { offset_y: f32, content_height: f32, viewport_height: f32, dragging: bool, drag_grab: f32 }
impl ScrollState { fn max_offset(self) -> f32 {(self.content_height-self.viewport_height).max(0.0)} fn set_offset(&mut self,y:f32){self.offset_y=y.max(0.0).min(self.max_offset());} }
type ClickHandler = Box<dyn FnMut(&mut Ui)>;

pub struct Ui { taffy:TaffyTree<NodeCtx>, widgets:Vec<Box<dyn Widget>>, widget_nodes:Vec<NodeId>, widget_clips:Vec<Option<Rect>>, clicks:Vec<Option<ClickHandler>>, scrolls:Vec<ScrollState>, scroll_nodes:Vec<NodeId>, scroll_contents:Vec<NodeId>, scroll_rects:Vec<Rect>, root:NodeId, root_w:u32, root_h:u32, focus:Option<WidgetId>, hovered:Option<WidgetId>, dirty:bool, dirty_rect:Option<Rect>, needs_layout:bool }
impl Ui {
 pub fn new()->Self{Self::with_size(1,1)}
 pub fn with_size(w:u32,h:u32)->Self{let mut taffy=TaffyTree::new();let mut style=Style::default();style.flex_direction=FlexDirection::Column;style.size=TSize{width:Dimension::length(w.max(1)as f32),height:Dimension::length(h.max(1)as f32)};let root=taffy.new_leaf(style).expect("taffy: create root");Self{taffy,widgets:Vec::new(),widget_nodes:Vec::new(),widget_clips:Vec::new(),clicks:Vec::new(),scrolls:Vec::new(),scroll_nodes:Vec::new(),scroll_contents:Vec::new(),scroll_rects:Vec::new(),root,root_w:w.max(1),root_h:h.max(1),focus:None,hovered:None,dirty:true,dirty_rect:None,needs_layout:true}}
 pub fn root(&self)->NodeId{self.root} pub fn root_node(&self)->NodeId{self.root} pub fn root_size(&self)->(u32,u32){(self.root_w,self.root_h)}
 pub fn style(&mut self,node:NodeId,update:impl FnOnce(&mut Style))->bool{let Some(mut style)=self.taffy.style(node).ok().cloned()else{return false};update(&mut style);if self.taffy.set_style(node,style).is_ok(){self.needs_layout=true;true}else{false}}
 pub fn set_style(&mut self,node:NodeId,style:Style)->bool{if self.taffy.set_style(node,style).is_ok(){self.needs_layout=true;true}else{false}}
 pub fn column(&mut self,parent:NodeId)->NodeId{self.container(parent,FlexDirection::Column)} pub fn row(&mut self,parent:NodeId)->NodeId{self.container(parent,FlexDirection::Row)} pub fn flex(&mut self,parent:NodeId,direction:FlexDirection)->NodeId{self.container(parent,direction)}
 fn container(&mut self,parent:NodeId,direction:FlexDirection)->NodeId{let mut s=Style::default();s.flex_direction=direction;let n=self.taffy.new_leaf(s).expect("taffy: create container");self.taffy.add_child(parent,n).expect("taffy: add container");self.needs_layout=true;n}
 pub fn panel(&mut self,parent:NodeId)->NodeId{let mut s=Style::default();s.flex_direction=FlexDirection::Column;s.padding=taffy::geometry::Rect{left:LP::length(8.0),right:LP::length(8.0),top:LP::length(8.0),bottom:LP::length(8.0)};let n=self.taffy.new_leaf_with_context(s,NodeCtx::Panel).expect("taffy: create panel");self.taffy.add_child(parent,n).expect("taffy: add panel");self.needs_layout=true;n}
 pub fn spacer(&mut self,parent:NodeId)->NodeId{let mut s=Style::default();s.flex_grow=1.0;let n=self.taffy.new_leaf(s).expect("taffy: create spacer");self.taffy.add_child(parent,n).expect("taffy: add spacer");self.needs_layout=true;n}
 pub fn scroll_view(&mut self,parent:NodeId)->ScrollViewId{let sid=ScrollViewId(self.scrolls.len());let mut viewport=Style::default();viewport.flex_direction=FlexDirection::Column;viewport.min_size.height=LPA::length(0.0);viewport.overflow=taffy::geometry::Point{x:Overflow::Hidden,y:Overflow::Hidden};let node=self.taffy.new_leaf_with_context(viewport,NodeCtx::ScrollView(sid)).expect("taffy: create scroll view");let mut content=Style::default();content.flex_direction=FlexDirection::Column;content.flex_shrink=0.0;content.min_size.height=LPA::length(0.0);content.size.width=Dimension::percent(1.0);let content_node=self.taffy.new_leaf_with_context(content,NodeCtx::ScrollContent(sid)).expect("taffy: create scroll content");self.taffy.add_child(node,content_node).expect("taffy: add scroll content");self.taffy.add_child(parent,node).expect("taffy: add scroll view");self.scrolls.push(ScrollState::default());self.scroll_nodes.push(node);self.scroll_contents.push(content_node);self.scroll_rects.push(Rect::default());self.needs_layout=true;sid}
 pub fn scroll_content(&self,scroll:ScrollViewId)->Option<NodeId>{self.scroll_contents.get(scroll.0).copied()} pub fn scroll_offset(&self,scroll:ScrollViewId)->Option<f32>{self.scrolls.get(scroll.0).map(|s|s.offset_y)} pub fn scroll_max_offset(&self,scroll:ScrollViewId)->Option<f32>{self.scrolls.get(scroll.0).map(|s|s.max_offset())}
 pub fn scroll_by(&mut self,scroll:ScrollViewId,dy:f32)->bool{let changed=if let Some(s)=self.scrolls.get_mut(scroll.0){let old=s.offset_y;s.set_offset(old+dy);old!=s.offset_y}else{false};if changed{self.apply_layout();self.mark_dirty_rect(self.scroll_rects[scroll.0]);}changed}
 pub fn scroll_to(&mut self,scroll:ScrollViewId,y:f32)->bool{let changed=if let Some(s)=self.scrolls.get_mut(scroll.0){let old=s.offset_y;s.set_offset(y);old!=s.offset_y}else{false};if changed{self.apply_layout();self.mark_dirty_rect(self.scroll_rects[scroll.0]);}changed}
 pub fn scroll_to_top(&mut self,scroll:ScrollViewId)->bool{self.scroll_to(scroll,0.0)} pub fn scroll_to_bottom(&mut self,scroll:ScrollViewId)->bool{self.scroll_max_offset(scroll).map(|y|self.scroll_to(scroll,y)).unwrap_or(false)}
 pub fn button(&mut self,parent:NodeId,label:&str)->WidgetId{let mut s=Style::default();s.justify_content=Some(JustifyContent::CENTER);s.align_items=Some(AlignItems::CENTER);s.padding=taffy::geometry::Rect{left:LP::length(12.0),right:LP::length(12.0),top:LP::length(5.0),bottom:LP::length(5.0)};self.add_widget(parent,Box::new(Button::new(label)),s)}
 pub fn label(&mut self,parent:NodeId,text:&str)->WidgetId{self.add_widget(parent,Box::new(Label::new(text)),Style::default())}
 pub fn text_input(&mut self,parent:NodeId)->WidgetId{self.text_input_with(parent,"")} pub fn text_input_with(&mut self,parent:NodeId,text:&str)->WidgetId{let mut s=Style::default();s.align_items=Some(AlignItems::CENTER);s.min_size=TSize{width:LPA::auto(),height:LPA::length(26.0)};s.padding=taffy::geometry::Rect{left:LP::length(6.0),right:LP::length(6.0),top:LP::length(4.0),bottom:LP::length(4.0)};self.add_widget(parent,Box::new(TextInput::new(text)),s)}
 fn add_widget(&mut self,parent:NodeId,widget:Box<dyn Widget>,style:Style)->WidgetId{let id=WidgetId(self.widgets.len());let node=self.taffy.new_leaf_with_context(style,NodeCtx::Widget(id)).expect("taffy: create widget");self.taffy.add_child(parent,node).expect("taffy: add widget");self.widgets.push(widget);self.widget_nodes.push(node);self.widget_clips.push(None);self.clicks.push(None);self.needs_layout=true;id}
 pub fn button_mut(&mut self,id:WidgetId)->Option<&mut Button>{self.widgets.get_mut(id.0)?.as_any_mut().downcast_mut::<Button>()} pub fn label_mut(&mut self,id:WidgetId)->Option<&mut Label>{self.widgets.get_mut(id.0)?.as_any_mut().downcast_mut::<Label>()} pub fn text_input_mut(&mut self,id:WidgetId)->Option<&mut TextInput>{self.widgets.get_mut(id.0)?.as_any_mut().downcast_mut::<TextInput>()}
 pub fn text(&self,id:WidgetId)->Option<&str>{let w=self.widgets.get(id.0)?;w.as_any().downcast_ref::<TextInput>().map(|v|v.text()).or_else(||w.as_any().downcast_ref::<Label>().map(|v|v.text()))}
 pub fn set_label(&mut self,id:WidgetId,text:&str){if let Some(v)=self.label_mut(id){v.set_text(text);self.needs_layout=true;}} pub fn set_button_label(&mut self,id:WidgetId,text:&str){if let Some(v)=self.button_mut(id){v.set_label(text);self.needs_layout=true;}} pub fn set_text(&mut self,id:WidgetId,text:&str){if let Some(v)=self.text_input_mut(id){v.set_text(text);self.mark_dirty_rect(self.widgets[id.0].rect());}}
 pub fn on_click<F:FnMut(&mut Ui)+'static>(&mut self,id:WidgetId,f:F){if let Some(slot)=self.clicks.get_mut(id.0){*slot=Some(Box::new(f));}} pub fn rect(&self,id:WidgetId)->Option<Rect>{self.widgets.get(id.0).map(|w|w.rect())} pub fn node_of(&self,id:WidgetId)->Option<NodeId>{self.widget_nodes.get(id.0).copied()} pub fn focus(&self)->Option<WidgetId>{self.focus}
 pub fn set_focus(&mut self,id:Option<WidgetId>){if self.focus==id{return}let old_focus=self.focus;if let Some(old)=old_focus{if let Some(w)=self.widgets.get_mut(old.0){w.set_focused(false)}}self.focus=id;if let Some(new)=id{if let Some(w)=self.widgets.get_mut(new.0){w.set_focused(true)}}if let Some(old)=old_focus{self.mark_dirty_rect(self.widgets[old.0].rect())}if let Some(new)=id{self.mark_dirty_rect(self.widgets[new.0].rect())}}
 pub fn request_full_redraw(&mut self){self.dirty=true;self.dirty_rect=None;self.needs_layout=true}
 fn mark_dirty_rect(&mut self,rect:Rect){self.dirty=true;self.dirty_rect=match self.dirty_rect{None=>Some(rect),Some(old)=>{let x0=old.x.min(rect.x);let y0=old.y.min(rect.y);let x1=(old.x+old.w as i32).max(rect.x+rect.w as i32);let y1=(old.y+old.h as i32).max(rect.y+rect.h as i32);Some(Rect::new(x0,y0,(x1-x0)as u32,(y1-y0)as u32))}}}
 pub fn process(&mut self,win:&mut Window){let mut events=[WmEvent::default();256];let n=win.poll_events(&mut events);self.set_root_size(win.client_width().max(1),win.client_height().max(1));if self.needs_layout{self.compute();self.needs_layout=false;self.dirty=true;self.dirty_rect=None}for raw in &events[..n]{let ev=match raw.kind{EV_MOUSE_DOWN=>UiEvent::Down{x:raw.a,y:raw.b},EV_MOUSE_UP=>UiEvent::Up{x:raw.a,y:raw.b},EV_MOUSE_MOVE=>UiEvent::Move{x:raw.a,y:raw.b},EV_KEY_DOWN=>UiEvent::KeyDown{scancode:raw.a as u8,ch:raw.b as u8,mods:raw.c as u8},EV_KEY_UP=>UiEvent::KeyUp{scancode:raw.a as u8,ch:raw.b as u8,mods:raw.c as u8},_=>continue};let mut clicked=None;if self.dispatch(&ev,&mut clicked){self.dirty=true}if let Some(id)=clicked{let mut cb=self.clicks[id.0].take();if let Some(f)=cb.as_mut(){f(self)}self.clicks[id.0]=cb}}for i in 0..self.widgets.len(){if self.widgets[i].dirty(){self.mark_dirty_rect(self.widgets[i].rect())}}if self.dirty{let rect=self.dirty_rect.unwrap_or(Rect::new(0,0,self.root_w,self.root_h));self.draw_rect(win,rect);let _=win.flip_rect(Rectangle::new(Point::new(rect.x,rect.y),Size::new(rect.w,rect.h)));self.dirty=false;self.dirty_rect=None;for w in &mut self.widgets{w.clear_dirty()}}}
 pub fn set_root_size(&mut self,w:u32,h:u32){let w=w.max(1);let h=h.max(1);if w==self.root_w&&h==self.root_h{return}self.root_w=w;self.root_h=h;let _=self.style(self.root,|s|{s.size=TSize{width:Dimension::length(w as f32),height:Dimension::length(h as f32)}})}
 fn compute(&mut self){let root=self.root;let rw=self.root_w;let rh=self.root_h;let widgets=&self.widgets;let taffy=&mut self.taffy;let space=TSize{width:AvailableSpace::Definite(rw as f32),height:AvailableSpace::Definite(rh as f32)};let _=taffy.compute_layout_with_measure(root,space,|inputs,_node,node_context,style|{taffy::compute_leaf_layout(inputs,style,|_value,_basis|0.0,|known,available|match node_context.as_deref(){Some(NodeCtx::Widget(id))=>widgets[id.0].measure(constraints_from_taffy(known,available)),_=>TSize::ZERO})});self.update_scroll_metrics();self.apply_layout()}
 fn update_scroll_metrics(&mut self){for i in 0..self.scrolls.len(){let v=self.taffy.layout(self.scroll_nodes[i]).ok().copied();let c=self.taffy.layout(self.scroll_contents[i]).ok().copied();if let(Some(v),Some(c))=(v,c){self.scrolls[i].viewport_height=v.size.height;self.scrolls[i].content_height=c.size.height;let off=self.scrolls[i].offset_y;self.scrolls[i].set_offset(off)}}}
 fn apply_layout(&mut self){for clip in &mut self.widget_clips{*clip=None}for rect in &mut self.scroll_rects{*rect=Rect::default()}self.apply_layout_node(self.root,0.0,0.0,None)}
 fn apply_layout_node(&mut self,node:NodeId,parent_x:f32,parent_y:f32,inherited_clip:Option<Rect>){let Ok(layout)=self.taffy.layout(node).copied()else{return};let ctx=self.taffy.get_node_context(node).copied();let mut screen_x=parent_x+layout.location.x;let mut screen_y=parent_y+layout.location.y;if let Some(NodeCtx::ScrollContent(sid))=ctx{screen_y-=self.scrolls[sid.0].offset_y;}let rect=Rect::new(screen_x.round()as i32,screen_y.round()as i32,layout.size.width.max(0.0).round()as u32,layout.size.height.max(0.0).round()as u32);let mut clip=inherited_clip;if let Some(NodeCtx::ScrollView(sid))=ctx{self.scroll_rects[sid.0]=rect;clip=match clip{Some(existing)=>existing.intersect(rect),None=>Some(rect)}}if let Some(NodeCtx::Widget(id))=ctx{self.widgets[id.0].set_rect(rect);self.widget_clips[id.0]=clip}let child_x=rect.x as f32;let child_y=rect.y as f32;let children:Vec<NodeId>=self.taffy.child_ids(node).collect();for child in children{self.apply_layout_node(child,child_x,child_y,clip)}}
 fn dispatch(&mut self,event:&UiEvent,clicked:&mut Option<WidgetId>)->bool{match event{UiEvent::Down{x,y}=>{if let Some((sid,grab))=self.scrollbar_at(*x,*y){if let Some(s)=self.scrolls.get_mut(sid.0){s.dragging=true;s.drag_grab=grab}return true}let target=self.hit_test(*x,*y);self.hovered=target;if let Some(id)=target{if self.widgets[id.0].focusable(){self.set_focus(Some(id))}let r=self.widgets[id.0].event(event,self.focus==Some(id));if r==EventResult::Clicked{*clicked=Some(id)}return r!=EventResult::Ignored}false}UiEvent::Move{x,y}=>{let mut changed=false;for i in 0..self.scrolls.len(){if !self.scrolls[i].dragging{continue}let sid=ScrollViewId(i);let v=self.scroll_rects[i];let(_thumb_top,thumb_h)=self.scrollbar_geometry(sid,v);let track_h=v.h as f32;let rel=(*y as f32-v.y as f32-self.scrolls[i].drag_grab).max(0.0).min((track_h-thumb_h).max(0.0));let max=self.scrolls[i].max_offset();let off=if track_h<=thumb_h{0.0}else{rel/(track_h-thumb_h)*max};changed|=self.scroll_to(sid,off)}let target=self.hit_test(*x,*y);if target!=self.hovered{if let Some(old)=self.hovered{let r=self.widgets[old.0].event(event,self.focus==Some(old));changed|=r!=EventResult::Ignored||self.widgets[old.0].dirty()}if let Some(new)=target{let r=self.widgets[new.0].event(event,self.focus==Some(new));changed|=r!=EventResult::Ignored||self.widgets[new.0].dirty()}self.hovered=target}changed}UiEvent::Up{x,y}=>{let mut changed=false;for s in &mut self.scrolls{if s.dragging{changed=true}s.dragging=false}if let Some(id)=self.hovered.or_else(||self.hit_test(*x,*y)){let r=self.widgets[id.0].event(event,self.focus==Some(id));changed|=r!=EventResult::Ignored||self.widgets[id.0].dirty()}self.hovered=self.hit_test(*x,*y);changed}UiEvent::KeyDown{..}|UiEvent::KeyUp{..}=>{if let Some(id)=self.focus{let r=self.widgets[id.0].event(event,true);if r==EventResult::Submitted&&self.clicks.get(id.0).map(|v|v.is_some()).unwrap_or(false){*clicked=Some(id)}r!=EventResult::Ignored}else{false}}}}
 fn hit_test(&self,x:i32,y:i32)->Option<WidgetId>{for i in(0..self.widgets.len()).rev(){let r=self.widgets[i].rect();if!r.contains(x,y){continue}if let Some(clip)=self.widget_clips[i]{if!clip.contains(x,y){continue}}return Some(WidgetId(i))}None}
 fn scrollbar_geometry(&self,sid:ScrollViewId,r:Rect)->(f32,f32){let s=self.scrolls[sid.0];let h=r.h as f32;if h<=0.0||s.content_height<=0.0{return(0.0,h)}let thumb_h=(h*(s.viewport_height/s.content_height.max(s.viewport_height))).max(12.0).min(h);let travel=(h-thumb_h).max(0.0);let top=if s.max_offset()<=0.0{0.0}else{(s.offset_y/s.max_offset())*travel};(top,thumb_h)}
 fn scrollbar_at(&self,x:i32,y:i32)->Option<(ScrollViewId,f32)>{for i in(0..self.scrolls.len()).rev(){let r=self.scroll_rects[i];if self.scrolls[i].content_height<=self.scrolls[i].viewport_height||r.h==0{continue}let xr=r.x+r.w as i32-10;if x<xr||x>r.x+r.w as i32||y<r.y||y>r.y+r.h as i32{continue}let sid=ScrollViewId(i);let(thumb_top,thumb_h)=self.scrollbar_geometry(sid,r);let local=(y-r.y)as f32;let grab=(local-thumb_top).max(0.0).min(thumb_h);return Some((sid,grab))}}None}
 fn draw_rect(&self,win:&mut Window,dirty:Rect){let screen=Rect::new(0,0,self.root_w,self.root_h);let Some(dirty)=dirty.intersect(screen)else{return};let clip=Rectangle::new(Point::new(dirty.x,dirty.y),Size::new(dirty.w,dirty.h));win.set_clip(Some(clip));let _=Rectangle::new(Point::new(dirty.x,dirty.y),Size::new(dirty.w,dirty.h)).into_styled(PrimitiveStyle::with_fill(BG)).draw(win);self.draw_node(self.root,win,clip);self.draw_scrollbars(win);win.set_clip(None)}
 fn draw_node(&self,node:NodeId,win:&mut Window,base_clip:Rectangle){let Ok(layout)=self.taffy.layout(node)else{return};let ctx=self.taffy.get_node_context(node).copied();if let Some(NodeCtx::Widget(id))=ctx{let r=self.widgets[id.0].rect();let visible=self.widget_clips[id.0].map(|c|r.intersect(c).is_some()).unwrap_or(true)&&r.intersect(Rect::new(0,0,self.root_w,self.root_h)).is_some();if visible{let clip=self.widget_clips[id.0].and_then(|c|c.intersect(Rect::new(0,0,self.root_w,self.root_h)));if let Some(c)=clip{win.intersect_clip(Rectangle::new(Point::new(c.x,c.y),Size::new(c.w,c.h)))}self.widgets[id.0].draw(win);win.set_clip(Some(base_clip))}return}let children:Vec<NodeId>=self.taffy.child_ids(node).collect();for child in children{self.draw_node(child,win,base_clip)}let _=layout}
 fn draw_scrollbars(&self,win:&mut Window){for i in 0..self.scrolls.len(){if self.scrolls[i].content_height<=self.scrolls[i].viewport_height{continue}let r=self.scroll_rects[i];if r.w==0||r.h==0{continue}let x=r.x+r.w as i32-10;let y=r.y;let h=r.h;let(thumb_top,thumb_h)=self.scrollbar_geometry(ScrollViewId(i),r);let _=Rectangle::new(Point::new(x,y),Size::new(10,h)).into_styled(PrimitiveStyle::with_fill(SCROLLBAR_BG)).draw(win);let _=Rectangle::new(Point::new(x,y+thumb_top.round()as i32),Size::new(10,thumb_h.round()as u32)).into_styled(PrimitiveStyle::with_fill(SCROLLBAR_THUMB)).draw(win)}}
}
fn constraints_from_taffy(known:TSize<Option<f32>>,available:TSize<AvailableSpace>)->Constraints{fn max(v:AvailableSpace)->f32{match v{AvailableSpace::Definite(v)=>v,AvailableSpace::MinContent=>0.0,AvailableSpace::MaxContent=>f32::INFINITY}}Constraints{min_width:known.width.unwrap_or(0.0),max_width:max(available.width),min_height:known.height.unwrap_or(0.0),max_height:max(available.height)}}
impl Default for Ui{fn default()->Self{Self::new()}}
impl Rect{fn from_taffy(l:&taffy::tree::Layout)->Self{Self::new(l.location.x.round()as i32,l.location.y.round()as i32,l.size.width.max(0.0).round()as u32,l.size.height.max(0.0).round()as u32)}}