[package]
name = "libfelix"
version = "0.1.0"
edition = "2021"

[lib]
test = false

[dependencies]
embedded-graphics = { version = "0.8.2", default-features = false }
embedded-graphics-unicodefonts = "0.2.0"
edge-http = { version = "0.8", default-features = false }
edge-nal = { version = "0.7", default-features = false }
embedded-io = { version = "0.7", features = ["alloc", "defmt"] }
embedded-io-async = { version = "0.7", default-features = false }
rand_core = { version = "0.6", default-features = false }
embedded-tls = { version = "0.19", default-features = false }
httparse = { version = "1.10", default-features = false }
defmt = "1.1.1"
taffy = { version = "0.14", default-features = false, features = ["alloc", "flexbox", "taffy_tree"] }

#rand_core_06 = { package = "rand_core", version = "0.6", default-features = false }