[package]
name = "twitch-radio"
version.workspace = true
edition.workspace = true

[[bin]]
name = "twitch-radio"
path = "src/main.rs"

[build-dependencies]

[dependencies]
dlmalloc = "0.2.14"
getrandom = { version = "0.2.17", features = ["custom"] }
libm = "0.2"
reqwest = { version = "=0.12.26", default-features = false, features = ["json", "rustls-tls-manual-roots-no-provider"] }
popugos = { path = "../../popugos" }
rusty_h264-common = { version = "0.16.0", default-features = false, features = ["std", "libm"] }
rusty_h264-decoder = { version = "0.16.0", default-features = false, features = ["std", "libm"] }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "custom-provider"] }
rustls-rustcrypto = "0.0.2-alpha"
sha2 = { version = "0.10.9", default-features = false, features = ["force-soft"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
symphonia = { version = "0.5.5", default-features = false, features = ["aac"] }
tokio = { version = "1.53.1", default-features = false, features = ["net", "rt", "rt-multi-thread", "sync", "time"] }
webpki-roots = "1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("popugos"))'] }
