[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = ["--cfg", "test_disabled", "--cfg", "getrandom_backend=\"custom\""]
target = ["x86_32-felix.json", "x86_16-felix.json"]

